export const iconMap = {
  "ir-blu": require("./icons/ir-blu.svg"),
  "ir-day": require("./icons/ir-day.svg"),
  "ir-eghtesad-novin": require("./icons/ir-eghtesad-novin.svg"),
  "ir-gardeshgari": require("./icons/ir-gardeshgari.svg"),
  "ir-iranzamin": require("./icons/ir-iranzamin.svg"),
  "ir-karafarin": require("./icons/ir-karafarin.svg"),
  "ir-keshavarzi": require("./icons/ir-keshavarzi.svg"),
  "ir-markazi": require("./icons/ir-markazi.svg"),
  "ir-maskan": require("./icons/ir-maskan.svg"),
  "ir-mehr": require("./icons/ir-mehr.svg"),
  "ir-mellat": require("./icons/ir-mellat.svg"),
  "ir-melli": require("./icons/ir-melli.svg"),
  "ir-parsian": require("./icons/ir-parsian.svg"),
  "ir-pasargad": require("./icons/ir-pasargad.svg"),
  "ir-post-bank": require("./icons/ir-post-bank.svg"),
  "ir-refah": require("./icons/ir-refah.svg"),
  "ir-resalat": require("./icons/ir-resalat.svg"),
  "ir-saderat": require("./icons/ir-saderat.svg"),
  "ir-saman": require("./icons/ir-saman.svg"),
  "ir-sanat-madan": require("./icons/ir-sanat-madan.svg"),
  "ir-sepah": require("./icons/ir-sepah.svg"),
  "ir-shahr": require("./icons/ir-shahr.svg"),
  "ir-sina": require("./icons/ir-sina.svg"),
  "ir-tejarat": require("./icons/ir-tejarat.svg"),
  "ir-tose-taawon": require("./icons/ir-tose-taawon.svg")
};
